site_name: yoyoengine docs
site_url: https://zoogies.github.io/yoyoengine/
repo_url: https://github.com/zoogies/yoyoengine
edit_uri: edit/main/docs/
theme:
  language: en
  direction: ltr
  name: material
  logo: assets/cleanlogo.png
  favicon: assets/cleanlogo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    tag:
      lua: simple/lua
      c: simple/c
      engine: fontawesome/solid/gears
      editor: fontawesome/solid/paint-roller
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.top
    - toc.follow
    - navigation.indexes
  font:
    text: Noto Sans
    code: Fira Code
    # code: Roboto Mono

extra:
  analytics:
    provider: google
    property: G-C10V5MEJ09
  version:
    provider: mike
  social:
    - icon: material/github
      link: https://github.com/zoogies/yoyoengine
  tags:
    lua: lua
    c: c
    engine: engine
    editor: editor
  consent:
    title: Data Consent
    description: >- 
      This site sends requests to Github (for documentation metadata) and Google Analytics (for user traffic statistics). Feel free to opt out :)

copyright: >
  Copyright &copy; 2023 - 2024 Ryan Zmuda -
  <a href="#__consent">Change cookie settings</a>

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: zoogies/yoyoengine
      branch: main
  - tags:
      tags_file: tags.md 
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  # - Getting Started:
  - index.md
  - Getting Started/getting_started.md
  - Feature Overview:
    - Plugins: Feature Overview/plugins.md
  - Scripting:
  #   - Scripting/C Scripting/c_scripting.md
    - Lua Scripting:
      - Scripting/Lua Scripting/overview.md
      - Scripting/Lua Scripting/systems.md
    - C Scripting:
      - Scripting/C Scripting/c_scripting.md
  #     # - Scripting/Lua Scripting/c_scripting.md